# Generated by Django 5.1.3 on 2024-11-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('isbn_no', models.PositiveIntegerField()),
                ('published_date', models.DateField()),
                ('price', models.CharField(max_length=250)),
                ('cover_pic', models.ImageField(null=True, upload_to='cover_pics')),
            ],
        ),
    ]
